<?php

namespace Database\Seeders;

use App\Models\Laboratory;
use Illuminate\Database\Seeder;

class LaboratorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $descriptions = [
            'Rayos x',
            'Quimica Sanguinea',
            'Tomografía computada multicorte',
            'Mastografía digital tomosintesis',
            'Densitometría',
            'Ultrasonido mamario volumétrico automatizado',
            'Elastografía ',
            'Radiología digital',
            'Ultrasonido',
            'Ultrasonido Doppler colon',
            'Biometría Hemática',
            'Ac. Anti Toxoplasma gondii IgG',
            'Velocidad de Eritrosedimentacion',
            'Reticulocitos',
            'Eosinofilos en moco nasal',
            'Plasmodium (busqueda en sangre)',
            'Grupo Sanguineo y factor Rh',
            'Ac. Anti Toxoplasma gondi IgM',
            'Ac. Anti Rubeola IgG',
            'Coombs Directo por Cromatografia',
            'Coombs Directo',
            'Coombs Indirecto',
            'Tiempo de Sangrado',
            'Tiempo de Protrombina (TP)',
            'Tiempo de Tromboplastina Parcial Activada (APPT)',
            'Tiempo de Trombina(3)',
            'Fibrinógeno',
            'Dimero D',
            'Factor VIII Antigenico(10)',
            'Inv. de Anticoag. circulantes',
            'Piruvato Cinasa(6)',
            'Antitrombina III (3)',
            'Plasminogeno(5)',
            'Factor IX de Coagulación (3)',
            'Factor VII de Coagulación(3)',
            'Factor de Von Willebrand (Antigenico)(3)',
            'Inhibidor del factor VIII(3)',
            'Inhibidor del Factor IX(3)',
            'Factor V Mutacion Leiden(8)',
            'Factor XI de Coagulacion(3)',
            'Cortisol (Estimulacion con cosintropina)',
            'Aminoacidos (cuantificacion)(25)',
            'Fragilidad Globular Osmotica (2)',
            'Hierro Total (Fe)',
            'Capacidad de Fijación de Hierro (UIBC)',
            'Enfermedad Mínima Residual(7)',
            'Aldolasa(3)',
            'Inmunofijación en suero(5)',
            'Glucosa',
            'Curva de Tolerancia a la Glucosa',
            'Glucosa Post Prandial',
            'Glucosa Post carga de 50g a una hora',
            'Urea (Suero)',
            'Creatinina(Suero)',
            'Acido Urico (Suero)',
            'Gamma Glutamil Transpeptidasa (GGT)',
            'Hemoglobina Glucosilada (HbA1c)',
            'Colesterol Total',
            'Perfil de Lípidos',
            'Colesterol de Baja Densidad (LDL)',
            'Bilirrubinas',
            'Multimeros del Factor VIII',
            'Amilasa (Suero)',
            'Proteínas Totales y Albumina',
            'Albumina (Suero)',
            'Proteinas del Suero y sus Fracciones',
            'Alanino Amino Transferasa (TGP/ALT)',
            'Aspartato Amino Transferasa (TGO/AST)',
            'Fosfatasa Alcalina',
            'Fosforo (Suero)',
            'Calcio (Suero)',
            'Cloro (Suero)',
            'Potasio (Suero)',
            'Sodio (Suero)',
            'Magnesio (Suero)',
            'Triglicéridos',
            'Creatin Fosfoquinasa (CPK)',
            'Creatin Fosfoquinasa Frac. MB (CK-MB)(3)',
            'Deshidrogenasa Lactica (LDH)',
            'Electroforesis de Hemoglobinas(7)',
            'Examen General de Orina',
            'Citoquimico de Liquido Cefalorraquideo',
            'Gasometría',
            'Gasometria con lactato',
            'Osmolaridad en Suero(3)',
            'Osmolaridad Urinaria(3)',
            'Cloro (Orina)',
            'Calcio (Orina)',
            'Sodio (Orina)',
            'Magnesio (Orina)',
            'Acido Urico (Orina)',
            'Amilasa (Orina)',
            'Ciclosporina(5)',
            'Carbamazepina (Tegretol) (5)',
            'Acido Valproico (Valproato, Depakene)(4)',
            'Antigeno de Virus Sincitial Respiratorio(4)',
            'Cultivo de tejido(5)',
            'Digoxina(3)',
            'Cultivo de Exudado Faringeo(5)',
            'Cultivo de Orina (Urocultivo)(3)',
            'Cultivo de exudado uretral(5)',
            'Cultivo de Esperma(5)',
            'Cultivo de Ex. Cervico vaginal(5)',
            'Hemocultivo(20)',
            'Cultivo de Secreción(5)',
            'Cultivo Nasal(5)',
            'Cultivo para Anaerobios(6)',
            'Cultivo Micologico (Hongos)(30)',
            'Cultivo de Liquido Cefalorraquideo(5)',
            'Cultivo de liquidos(5)',
            'Cultivo de Aspirado Bronquial(5)',
            'Coprocultivo(6)',
            'Tincion de Gram',
            'Tincion de Kinyoun(2)',
            'Interleucina 6 IL-6(12)',
            'Coprologico',
            'Sangre Oculta en Heces',
            'Amiba en fresco',
            'Azucares Reductores (Heces)',
            'Serotonina, Ac. 5-OH-indolacetico (ORINA)(8)',
            'Normetanefrinas en Orina(5)',
            'Prueba Inmunologica de Embarazo',
            'Influenza A, B (cromatografia)',
            'Hepatitis B(Cromatografia)',
            'Cofactor de Ristocetina',
            'Ac. Anti Cardiolipina IgA',
            'Ac. Anti b2Glicoproteina IgA',
            'Inmunoglobulina D (IgD)(4)',
            'Ac. Anti Nucleares (Hep2)(4)',
            'Ac. Anti DNA doble cadena (Nativo) (3)',
            'Ac. Anti Sm (Smith)(3)',
            'Ac. Anti RNP (ENA) (3)',
            'Ac. Anti SSA/SSB(Ro/La)(5)',
            'Ac. Anti Jo-1 IgG(3)',
            'AC. Anti Cardiolipinas (IgG,IgM)(3)',
            'Inmunoglobulina G (IgG)',
            'Inmunoglobulina A (IgA)',
            'Inmunoglobulina M (IGM)',
            'Inmunoglobulina E (IGE)(Ma-Vi)',
            'Colinesterasa(3)',
            'Complemento C4',
            'Ac. Anti Rubeola (IgG, IgM)',
            'Ac. Anti Citomegalovirus (IgG, IgM )',
            'Microalbúmina (Orina)',
            'Ac. Anti Toxoplasma Gondi (IgG,IgM)',
            'IgE Específica(4)',
            'Ac. Anti Herpes 1+2 (IgG e IgM)',
            'Ac. Anti Treponema pallidum (FTA-ABS)(6)',
            'PCR para Mycobacterium tuberculosis(8)',
            'Cadenas ligeras kappa y lambda en suero (3)',
            'Cadenas ligeras kappa y lambda en Orina(3)',
            'PCR para Herpes Simplex',
            'Ac. Anti Sindrome Paraneoplasico',
            'Perfil ANCAS (7)',
            'Proteina C Reactiva',
            'Antiestreptolisina O',
            'Factor Reumatoide',
            'Ac. Anti Treponema pallidum(VDRL)',
            'Reacciones Febriles',
            'Mioglobina(4)',
            'Ac. Anti Dengue IgG e IgM(6)',
            'Carga Viral para VHC(8)',
            'Ferritina',
            'Beta 2 Microglobulina(3)',
            'Vitamina B-12 (5)',
            'Intradermorreacción al PPD(4)',
            'Creatinina (Orina)',
            'Fósforo (Orina)',
            'Cultivo de cateter(5)',
            'Complemento Hemolítico al 50%(Lu-Ju)',
            'Ac. Anti VIH1 y 2/ Ag P24',
            'Ac. Anti Listeria(10)',
            'Ac. Anti Mycoplasma pneumoniae(3)',
            'Transferrina(2)',
            'Ac. Anti Musculo Liso(6)',
            'Ac. Anti Mitocondriales(3)',
            'Virus Hepatitis C (HVC) Ac./Ag',
            'Antigeno de Superficie de Virus Hepatitis B (HBsAg)',
            'Difenilhidantoina (Fenitoina)(3)',
            'Ac. Anti Parvovirus B-19(3)',
            'HE4 (Proteina 4 del epididimo humano)(3)',
            'Coproparasitoscopico (1-3)',
            'Ac. Anti Centromero(3)',
            'Cultivo de Liquido Peritoneal(5)',
            'Acido Folico (3)',
            'Eritropoyetina(3)',
            'Urea (Orina)',
            'Cultivo de Expectoracion(5)',
            'PCR para Parvovirus B19(5)',
            'Perfil de Inmunoglobulinas',
            'Amonio',
            'Curva Insulina (6 muestras)',
            'BAAR (3 muestras)(3)',
            'Lipasa',
            'Lactato (Ac. Lactico)(3)',
            'Troponina',
            '4K Score (solo Ma)(10)',
            'Perfil CMU(5)',
            'Glucosa en orina de 24 Hrs',
            'Estimulacion con CLONIDINA(1)',
        ];
        foreach ($descriptions as $description) {
            Laboratory::create([
                'description' => $description,
                'status' => 'ACTIVO'
            ]);
        }
    }
}
